language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:
  - pip instaall test_env.txt
  - pip install Django~=$DJANGO_VERSION

script:
  - python logtest/manage.py test automated_logging
