language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.1
  - DJANGO_VERSION=3.2

install:
  - sudo apt-get update -y
  - sudo apt-get install -y sqlite3
  - pip install poetry
  - poetry add "django~${DJANGO_VERSION}"

script:
  - poetry run python tests/run.py

after_success:
  - poetry run coveralls
