language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:
  - pip install -r requirements_dev.txt
  - pip install Django~=$DJANGO_VERSION

script:
  - ls -lah
  - coverage run --source=automated_logging logtest/manage.py test automated_logging
  - cat .coverage
  - ls -lah

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
