language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2

matrix:
  exclude:
    - python: "3.4"
      env: "DJANGO_VERSION=2.1"

    - python: "3.4"
      env: "DJANGO_VERSION=2.2"

install:
  - sudo apt-get install -y sqlite3
  - pip install -r requirements.dev.txt
  - pip install Django~=$DJANGO_VERSION

script:
  - coverage run --source=automated_logging logtest/manage.py test automated_logging

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
