# Generated by Django 3.0.7 on 2020-06-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automated_logging', '0016_auto_20200620_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
