# Generated by Django 3.0.7 on 2020-07-01 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_logging', '0017_auto_20200620_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrelationshipmodification',
            name='operation',
            field=models.SmallIntegerField(choices=[(1, 'create'), (0, 'modify'), (-1, 'delete')], null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='modelvaluemodification',
            name='operation',
            field=models.SmallIntegerField(choices=[(1, 'create'), (0, 'modify'), (-1, 'delete')], null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
