# Generated by Django 3.0.7 on 2020-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_logging', '0018_auto_20200701_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelevent',
            options={'verbose_name': 'Model Event', 'verbose_name_plural': 'Model Events'},
        ),
        migrations.AlterModelOptions(
            name='unspecifiedevent',
            options={'verbose_name': 'Unspecified Event', 'verbose_name_plural': 'Unspecified Events'},
        ),
        migrations.AddField(
            model_name='requestevent',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
