# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.Base'),
        ),
        migrations.AlterField(
            model_name='m2mtest',
            name='test',
            field=models.ManyToManyField(null=True, to='testmodels.Base'),
        ),
        migrations.AlterField(
            model_name='onetoonetest',
            name='test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testmodels.Base'),
        ),
        migrations.AlterField(
            model_name='ordinarytest',
            name='test',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
