# Generated by Django 2.0.2 on 2018-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0002_auto_20180216_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2mtest',
            name='test',
            field=models.ManyToManyField(to='testmodels.Base'),
        ),
    ]
